version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_USER=developer
      - INFLUXDB_USER_PASSWORD=developer
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - 127.0.0.1:8086:8086
  grafana:
    image: docker.io/grafana/grafana
    ports:
      - 3000:3000
    depends_on: ['influxdb']
